-----we have used this sql on test_parquet_final.py while migrating columns of source SQLSERVER table 
-- into parquet file. However, if you want exact metadata of columns, skip the column
--on query and later explicilty define on DataWarehouse schema definition.

SELECT 
    Tranno,
    refno,
    agentid,
    agentname,
    Branch_code,
    Branch,
    CustomerId,
    SenderName,
    SenderAddress,
    SenderPhoneno,
    senderSalary,
    senderFax,
    SenderCity,
    SenderCountry,
    SenderEmail,
    SenderCompany,
    senderPassport,
    senderVisa,
    ReceiverName,
    ReceiverAddress,
    ReceiverPhone,
    ReceiverFax,
    ReceiverCity,
    ReceiverCountry,
    ReceiverRelation,
    ReceiverIDDescription,
    ReceiverID,
    DOT,
    DOtTime,
    paidAmt,
    paidCType,
    receiveAmt,
    receiveCType,
    ExchangeRate,
    Today_Dollar_rate,
    Dollar_Amt,
    SCharge,
    ReciverMessage,
    TestQuestion,
    TestAnswer,
    amtSenderType,
    SenderBankID,
    SenderBankName,
    SenderBankBranch,
    SenderBankVoucherNo,
    Amt_paid_date,
    paymentType,
    rBankID,
    rBankName,
    rBankBranch,
    rBankACNo,
    rBankAcType,
    otherCharge,
    TransStatus,
    status,
    SEmpID,
    bTno,
    imeCommission,
    bankCommission,
    TotalRoundAmt,
    TransferType,
    paidBy,
    paidDate,
    paidTime,
    courierID,
    PODDate,
    senderCommission,
    receiverCommission,
    approve_by,
    receiveAgentID,
    send_mode,
    confirmDate,
    lock_status,
    lock_dot,
    lock_by,
    local_DOT,
    sender_mobile,
    receiver_mobile,
    fax_trans,
    SenderNativeCountry,
    receiverEmail,
    ip_address,
    agent_dollar_rate,
    ho_dollar_rate,
    bonus_amt,
    request_for_new_account,
    trans_mode,
    digital_id_sender,
    digital_id_payout,
    expected_payoutagentid,
    bonus_value_amount,
    bonus_type,
    bonus_on,
    ben_bank_id,
    ben_bank_name,
    test_Trn,
    paid_agent_id,
    send_sms,
    agent_settlement_rate,
    agent_ex_gain,
    cancel_date,
    cancel_by,
    agent_receiverCommission,
    agent_receiverSCommission,
    door_to_door,
    CAST(customer_sno AS INT) AS customer_sno,
    paid_date_usd_rate,
    send_sms_ben,
    extBankCommission,
    authorization_code,
    id_type,
    backup_approve_ts,
    backup_approve_by,
    authorization_req_by
FROM [{TABLE_SCHEMA}].[{TABLE_NAME}]
WHERE DOT >= '2009-07-08 00:00:00.000'
  AND DOT <  '2015-06-03 00:00:00.000';

----I used this sql when i want to migrate data on csv. 
SELECT 
    CAST(Tranno AS VARCHAR(50)) AS Tranno,
    CAST(refno AS VARCHAR(500)) AS refno,
    CAST(agentid AS VARCHAR(500)) AS agentid,
    CAST(agentname AS VARCHAR(500)) AS agentname,
    CAST(Branch_code AS VARCHAR(500)) AS Branch_code,
    CAST(Branch AS VARCHAR(500)) AS Branch,
    CAST(CustomerId AS VARCHAR(500)) AS CustomerId,
    CAST(SenderName AS VARCHAR(500)) AS SenderName,
    CAST(SenderAddress AS VARCHAR(1000)) AS SenderAddress,
    CAST(SenderPhoneno AS VARCHAR(500)) AS SenderPhoneno,
    CAST(senderSalary AS VARCHAR(500)) AS senderSalary,
    CAST(senderFax AS VARCHAR(500)) AS senderFax,
    CAST(SenderCity AS VARCHAR(500)) AS SenderCity,
    CAST(SenderCountry AS VARCHAR(500)) AS SenderCountry,
    CAST(SenderEmail AS VARCHAR(500)) AS SenderEmail,
    CAST(SenderCompany AS VARCHAR(500)) AS SenderCompany,
    CAST(senderPassport AS VARCHAR(500)) AS senderPassport,
    CAST(senderVisa AS VARCHAR(500)) AS senderVisa,
    CAST(ReceiverName AS VARCHAR(500)) AS ReceiverName,
    CAST(ReceiverAddress AS VARCHAR(1000)) AS ReceiverAddress,
    CAST(ReceiverPhone AS VARCHAR(500)) AS ReceiverPhone,
    CAST(ReceiverFax AS VARCHAR(500)) AS ReceiverFax,
    CAST(ReceiverCity AS VARCHAR(500)) AS ReceiverCity,
    CAST(ReceiverCountry AS VARCHAR(500)) AS ReceiverCountry,
    CAST(ReceiverRelation AS VARCHAR(500)) AS ReceiverRelation,
    CAST(ReceiverIDDescription AS VARCHAR(500)) AS ReceiverIDDescription,
    CAST(ReceiverID AS VARCHAR(500)) AS ReceiverID,
    CONVERT(VARCHAR(30), DOT, 121) AS DOT,
    CAST(DOtTime AS VARCHAR(500)) AS DOtTime,
    CAST(paidAmt AS VARCHAR(100)) AS paidAmt,
    CAST(paidCType AS VARCHAR(500)) AS paidCType,
    CAST(receiveAmt AS VARCHAR(100)) AS receiveAmt,
    CAST(receiveCType AS VARCHAR(500)) AS receiveCType,
    CAST(ExchangeRate AS VARCHAR(100)) AS ExchangeRate,
    CAST(Today_Dollar_rate AS VARCHAR(100)) AS Today_Dollar_rate,
    CAST(Dollar_Amt AS VARCHAR(100)) AS Dollar_Amt,
    CAST(SCharge AS VARCHAR(100)) AS SCharge,
    CAST(ReciverMessage AS VARCHAR(MAX)) AS ReciverMessage,
    CAST(TestQuestion AS VARCHAR(MAX)) AS TestQuestion,
    CAST(TestAnswer AS VARCHAR(MAX)) AS TestAnswer,
    CAST(amtSenderType AS VARCHAR(500)) AS amtSenderType,
    CAST(SenderBankID AS VARCHAR(500)) AS SenderBankID,
    CAST(SenderBankName AS VARCHAR(500)) AS SenderBankName,
    CAST(SenderBankBranch AS VARCHAR(500)) AS SenderBankBranch,
    CAST(SenderBankVoucherNo AS VARCHAR(500)) AS SenderBankVoucherNo,
    CONVERT(VARCHAR(30), Amt_paid_date, 121) AS Amt_paid_date,
    CAST(paymentType AS VARCHAR(500)) AS paymentType,
    CAST(rBankID AS VARCHAR(500)) AS rBankID,
    CAST(rBankName AS VARCHAR(500)) AS rBankName,
    CAST(rBankBranch AS VARCHAR(500)) AS rBankBranch,
    CAST(rBankACNo AS VARCHAR(500)) AS rBankACNo,
    CAST(rBankAcType AS VARCHAR(500)) AS rBankAcType,
    CAST(otherCharge AS VARCHAR(100)) AS otherCharge,
    CAST(TransStatus AS VARCHAR(500)) AS TransStatus,
    CAST(status AS VARCHAR(500)) AS status,
    CAST(SEmpID AS VARCHAR(500)) AS SEmpID,
    CAST(bTno AS VARCHAR(500)) AS bTno,
    CAST(imeCommission AS VARCHAR(100)) AS imeCommission,
    CAST(bankCommission AS VARCHAR(100)) AS bankCommission,
    CAST(TotalRoundAmt AS VARCHAR(100)) AS TotalRoundAmt,
    CAST(TransferType AS VARCHAR(500)) AS TransferType,
    CAST(paidBy AS VARCHAR(500)) AS paidBy,
    CONVERT(VARCHAR(30), paidDate, 121) AS paidDate,
    CAST(paidTime AS VARCHAR(500)) AS paidTime,
    CAST(courierID AS VARCHAR(50)) AS courierID,
    CONVERT(VARCHAR(30), PODDate, 121) AS PODDate,
    CAST(senderCommission AS VARCHAR(100)) AS senderCommission,
    CAST(receiverCommission AS VARCHAR(100)) AS receiverCommission,
    CAST(approve_by AS VARCHAR(500)) AS approve_by,
    CAST(receiveAgentID AS VARCHAR(500)) AS receiveAgentID,
    CAST(send_mode AS VARCHAR(500)) AS send_mode,
    CONVERT(VARCHAR(30), confirmDate, 121) AS confirmDate,
    CAST(lock_status AS VARCHAR(500)) AS lock_status,
    CONVERT(VARCHAR(30), lock_dot, 121) AS lock_dot,
    CAST(lock_by AS VARCHAR(500)) AS lock_by,
    CONVERT(VARCHAR(30), local_DOT, 121) AS local_DOT,
    CAST(sender_mobile AS VARCHAR(500)) AS sender_mobile,
    CAST(receiver_mobile AS VARCHAR(500)) AS receiver_mobile,
    CAST(fax_trans AS VARCHAR(500)) AS fax_trans,
    CAST(SenderNativeCountry AS VARCHAR(500)) AS SenderNativeCountry,
    CAST(receiverEmail AS VARCHAR(500)) AS receiverEmail,
    CAST(ip_address AS VARCHAR(500)) AS ip_address,
    CAST(agent_dollar_rate AS VARCHAR(100)) AS agent_dollar_rate,
    CAST(ho_dollar_rate AS VARCHAR(100)) AS ho_dollar_rate,
    CAST(bonus_amt AS VARCHAR(100)) AS bonus_amt,
    CAST(request_for_new_account AS VARCHAR(500)) AS request_for_new_account,
    CAST(trans_mode AS VARCHAR(500)) AS trans_mode,
    CAST(digital_id_sender AS VARCHAR(500)) AS digital_id_sender,
    CAST(digital_id_payout AS VARCHAR(500)) AS digital_id_payout,
    CAST(expected_payoutagentid AS VARCHAR(500)) AS expected_payoutagentid,
    CAST(bonus_value_amount AS VARCHAR(100)) AS bonus_value_amount,
    CAST(bonus_type AS VARCHAR(500)) AS bonus_type,
    CAST(bonus_on AS VARCHAR(500)) AS bonus_on,
    CAST(ben_bank_id AS VARCHAR(500)) AS ben_bank_id,
    CAST(ben_bank_name AS VARCHAR(500)) AS ben_bank_name,
    CAST(test_Trn AS VARCHAR(500)) AS test_Trn,
    CAST(paid_agent_id AS VARCHAR(500)) AS paid_agent_id,
    CAST(send_sms AS VARCHAR(500)) AS send_sms,
    CAST(agent_settlement_rate AS VARCHAR(100)) AS agent_settlement_rate,
    CAST(agent_ex_gain AS VARCHAR(100)) AS agent_ex_gain,
    CONVERT(VARCHAR(30), cancel_date, 121) AS cancel_date,
    CAST(cancel_by AS VARCHAR(500)) AS cancel_by,
    CAST(agent_receiverCommission AS VARCHAR(100)) AS agent_receiverCommission,
    CAST(agent_receiverSCommission AS VARCHAR(100)) AS agent_receiverSCommission,
    CAST(door_to_door AS VARCHAR(500)) AS door_to_door,
    CAST(customer_sno AS VARCHAR(50)) AS customer_sno,
    CAST(paid_date_usd_rate AS VARCHAR(100)) AS paid_date_usd_rate,
    CAST(send_sms_ben AS VARCHAR(500)) AS send_sms_ben,
    CAST(extBankCommission AS VARCHAR(100)) AS extBankCommission,
    CAST(authorization_code AS VARCHAR(500)) AS authorization_code,
    CAST(id_type AS VARCHAR(500)) AS id_type,
    CONVERT(VARCHAR(30), backup_approve_ts, 121) AS backup_approve_ts,
    CAST(backup_approve_by AS VARCHAR(500)) AS backup_approve_by,
    CAST(authorization_req_by AS VARCHAR(500)) AS authorization_req_by
FROM dbo.moneysend 
WHERE DOT >= '2010-01-01 00:00:00.000'
  AND DOT <  '2015-06-03 00:00:00.000';